.TH UMANAGER 1 "JUNE 2023"
.SH NAME
umanager \- simplified user and group management
.
.SH SYNOPSIS
\fBumanager\fR [OPTIONS]
.
.SH DESCRIPTION
.br
\fBumanager\fR is a script that allows to add, remove and modify users and groups.
.br
It requires installed and configured vsftpd server to use all of its features.
.br
Program provides a simple gui that allows user to
.br
* Display all users and groups
.br
* Adding new users and groups
.br
* Modify users and groups parameters
.br
* Lock or disable user account
.br
* Set expiration date on an user account
.br
* Delete user accounts
.br
* Add user accounts as FTP
.br
* Managing disk quota
.br
* Informing users about their disk space left
.br
* Jailing FTP users
.br
* Adding only FTP users
.
.SH OPTIONS
.IP -h
Display help information and exit.
.IP -v
Display the version number and exit.
.IP -a
Lists all users and groups.
.IP -g
Lists all groups.
.IP -u
Lists all users.
.
.SH EXAMPLES
Example usages of \fBumanager\fR:
.IP "1."
Display a list of users:
.IP "2."
Add an existing user "john" to the group "developers":
.IP "3."
Reset the password for the user "jane":
.IP "4."
Change the username for the user "jake" to "jacob":
.
.SH AUTHOR
Łukasz Walczak \fIluk\.walczak1@gmail\.com\fR
.
.SH REPORTING BUGS
Report any bugs or issues to \fIluk\.walczak1@gmail\.com\fR\.
.
.SH COPYRIGHT
Copyright © 2023 Łukasz Walczak\. This is free software; see the source code for copying conditions\. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\.

